import type { Breed } from "./types";

// Part 2: Popular working, sporting, terriers
export const BREEDS_PART2: Breed[] = [
  {
    slug: "english-springer-spaniel",
    name: "English Springer Spaniel",
    group: "sporting",
    size: "medium",
    origin: "England",
    heightMaleMin: 19, heightMaleMax: 21, heightFemaleMin: 18, heightFemaleMax: 20,
    weightMaleMin: 50, weightMaleMax: 55, weightFemaleMin: 40, weightFemaleMax: 50,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 3, grooming: 3, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye conditions", "Ear infections", "Phosphofructokinase deficiency"],
    blurb: "A friendly, playful, obedient gundog — bred to spring game from cover for the hunter's net or gun.",
    temperament: ["Friendly", "Playful", "Obedient"],
  },
  {
    slug: "brittany",
    name: "Brittany",
    group: "sporting",
    size: "medium",
    origin: "France",
    heightMaleMin: 17.5, heightMaleMax: 20.5, heightFemaleMin: 17.5, heightFemaleMax: 20.5,
    weightMaleMin: 30, weightMaleMax: 40, weightFemaleMin: 30, weightFemaleMax: 40,
    lifespanMin: 12, lifespanMax: 14,
    energy: 5, trainability: 4, shedding: 3, grooming: 2, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Epilepsy", "Hypothyroidism"],
    blurb: "A bright, fun-loving, upbeat pointer-spaniel hybrid — energetic, athletic gundog and lively companion.",
    temperament: ["Bright", "Fun-Loving", "Upbeat"],
  },
  {
    slug: "weimaraner",
    name: "Weimaraner",
    group: "sporting",
    size: "large",
    origin: "Germany",
    heightMaleMin: 25, heightMaleMax: 27, heightFemaleMin: 23, heightFemaleMax: 25,
    weightMaleMin: 70, weightMaleMax: 90, weightFemaleMin: 55, weightFemaleMax: 75,
    lifespanMin: 11, lifespanMax: 14,
    energy: 5, trainability: 4, shedding: 2, grooming: 1, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 2, intelligence: 5, exerciseNeeds: 5, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Bloat", "Hip dysplasia", "Hypothyroidism", "Von Willebrand's disease"],
    blurb: "A friendly, fearless, obedient gundog with a striking silver-grey coat — the 'grey ghost' from Germany.",
    temperament: ["Friendly", "Fearless", "Obedient"],
  },
  {
    slug: "vizsla",
    name: "Vizsla",
    group: "sporting",
    size: "medium",
    origin: "Hungary",
    heightMaleMin: 22, heightMaleMax: 24, heightFemaleMin: 21, heightFemaleMax: 23,
    weightMaleMin: 55, weightMaleMax: 60, weightFemaleMin: 44, weightFemaleMax: 55,
    lifespanMin: 12, lifespanMax: 14,
    energy: 5, trainability: 5, shedding: 2, grooming: 1, barking: 2,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Epilepsy", "Hypothyroidism"],
    blurb: "An affectionate, energetic, gentle Hungarian pointer — the original 'velcro dog' that needs constant company.",
    temperament: ["Affectionate", "Energetic", "Gentle"],
  },
  {
    slug: "chesapeake-bay-retriever",
    name: "Chesapeake Bay Retriever",
    group: "sporting",
    size: "large",
    origin: "USA",
    heightMaleMin: 23, heightMaleMax: 26, heightFemaleMin: 21, heightFemaleMax: 24,
    weightMaleMin: 65, weightMaleMax: 80, weightFemaleMin: 55, weightFemaleMax: 70,
    lifespanMin: 10, lifespanMax: 13,
    energy: 4, trainability: 4, shedding: 4, grooming: 2, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 3, intelligence: 4, exerciseNeeds: 5, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Bloat"],
    blurb: "A bright, sensitive, affectionate water retriever from Maryland — tough enough for icy bay waters.",
    temperament: ["Bright", "Sensitive", "Affectionate"],
  },
  {
    slug: "cocker-spaniel",
    name: "Cocker Spaniel",
    group: "sporting",
    size: "small",
    origin: "USA",
    heightMaleMin: 14.5, heightMaleMax: 15.5, heightFemaleMin: 13.5, heightFemaleMax: 14.5,
    weightMaleMin: 25, weightMaleMax: 30, weightFemaleMin: 20, weightFemaleMax: 25,
    lifespanMin: 10, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 3, grooming: 4, barking: 4,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 2,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Eye conditions", "Ear infections", "Hip dysplasia", "Heart disease"],
    blurb: "A gentle, smart, happy gundog — Disney's Lady, with the gorgeous flowing coat and merry tail.",
    temperament: ["Gentle", "Smart", "Happy"],
  },
  {
    slug: "irish-setter",
    name: "Irish Setter",
    group: "sporting",
    size: "large",
    origin: "Ireland",
    heightMaleMin: 27, heightMaleMax: 27, heightFemaleMin: 25, heightFemaleMax: 25,
    weightMaleMin: 70, weightMaleMax: 70, weightFemaleMin: 60, weightFemaleMax: 60,
    lifespanMin: 12, lifespanMax: 15,
    energy: 5, trainability: 3, shedding: 3, grooming: 3, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 3, intelligence: 4, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Epilepsy", "Eye disorders"],
    blurb: "An active, outgoing, sweet-tempered gundog with a famous mahogany coat — exuberant and a little goofy.",
    temperament: ["Active", "Outgoing", "Sweet-Tempered"],
  },
  {
    slug: "english-cocker-spaniel",
    name: "English Cocker Spaniel",
    group: "sporting",
    size: "medium",
    origin: "England",
    heightMaleMin: 16, heightMaleMax: 17, heightFemaleMin: 15, heightFemaleMax: 16,
    weightMaleMin: 28, weightMaleMax: 34, weightFemaleMin: 26, weightFemaleMax: 32,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 3, grooming: 3, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Ear infections", "Eye disorders"],
    blurb: "A merry, sturdy, friendly gundog — the original woodcock specialist, leggier than its American cousin.",
    temperament: ["Merry", "Sturdy", "Friendly"],
  },
  {
    slug: "newfoundland",
    name: "Newfoundland",
    group: "working",
    size: "giant",
    origin: "Canada",
    heightMaleMin: 28, heightMaleMax: 28, heightFemaleMin: 26, heightFemaleMax: 26,
    weightMaleMin: 130, weightMaleMax: 150, weightFemaleMin: 100, weightFemaleMax: 120,
    lifespanMin: 9, lifespanMax: 10,
    energy: 2, trainability: 4, shedding: 5, grooming: 4, barking: 2,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 4,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 5,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Heart disease", "Bloat", "Cystinuria"],
    blurb: "A sweet, patient, devoted water-rescue dog — the gentle 'nanny dog' from Canada's Atlantic coast.",
    temperament: ["Sweet", "Patient", "Devoted"],
  },
  {
    slug: "saint-bernard",
    name: "Saint Bernard",
    group: "working",
    size: "giant",
    origin: "Switzerland",
    heightMaleMin: 28, heightMaleMax: 30, heightFemaleMin: 26, heightFemaleMax: 28,
    weightMaleMin: 140, weightMaleMax: 180, weightFemaleMin: 120, weightFemaleMax: 140,
    lifespanMin: 8, lifespanMax: 10,
    energy: 2, trainability: 4, shedding: 4, grooming: 3, barking: 2,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 5,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Heart disease", "Eye conditions"],
    blurb: "A playful, charming, inquisitive Alpine rescue giant — the original mountain rescue with the brandy keg.",
    temperament: ["Playful", "Charming", "Inquisitive"],
  },
  {
    slug: "mastiff",
    name: "Mastiff",
    group: "working",
    size: "giant",
    origin: "England",
    heightMaleMin: 30, heightMaleMax: 30, heightFemaleMin: 27.5, heightFemaleMax: 27.5,
    weightMaleMin: 160, weightMaleMax: 230, weightFemaleMin: 120, weightFemaleMax: 170,
    lifespanMin: 6, lifespanMax: 10,
    energy: 2, trainability: 3, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 5,
    adaptability: 3, intelligence: 3, exerciseNeeds: 2, droolingLevel: 5,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Heart disease", "Cancer"],
    blurb: "A courageous, dignified, good-natured giant — one of the most ancient breeds, formerly war dogs.",
    temperament: ["Courageous", "Dignified", "Good-Natured"],
  },
  {
    slug: "great-pyrenees",
    name: "Great Pyrenees",
    group: "working",
    size: "giant",
    origin: "France",
    heightMaleMin: 27, heightMaleMax: 32, heightFemaleMin: 25, heightFemaleMax: 29,
    weightMaleMin: 100, weightMaleMax: 100, weightFemaleMin: 85, weightFemaleMax: 85,
    lifespanMin: 10, lifespanMax: 12,
    energy: 2, trainability: 3, shedding: 5, grooming: 3, barking: 4,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 5,
    adaptability: 3, intelligence: 4, exerciseNeeds: 2, droolingLevel: 3,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Bone cancer", "Heart problems"],
    blurb: "A patient, smart, strong-willed livestock guardian — the snowy giant of the Pyrenees mountains.",
    temperament: ["Patient", "Smart", "Strong-Willed"],
  },
  {
    slug: "alaskan-malamute",
    name: "Alaskan Malamute",
    group: "working",
    size: "large",
    origin: "USA",
    heightMaleMin: 25, heightMaleMax: 25, heightFemaleMin: 23, heightFemaleMax: 23,
    weightMaleMin: 85, weightMaleMax: 85, weightFemaleMin: 75, weightFemaleMax: 75,
    lifespanMin: 10, lifespanMax: 14,
    energy: 4, trainability: 3, shedding: 5, grooming: 3, barking: 2,
    goodWithKids: 4, goodWithDogs: 2, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 2, intelligence: 4, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Cataracts", "Hypothyroidism", "Bloat"],
    blurb: "An affectionate, loyal, playful arctic freight dog — bigger and stronger than the Husky, equally fluffy.",
    temperament: ["Affectionate", "Loyal", "Playful"],
  },
  {
    slug: "samoyed",
    name: "Samoyed",
    group: "working",
    size: "medium",
    origin: "Russia",
    heightMaleMin: 21, heightMaleMax: 23.5, heightFemaleMin: 19, heightFemaleMax: 21,
    weightMaleMin: 45, weightMaleMax: 65, weightFemaleMin: 35, weightFemaleMax: 50,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 5, grooming: 4, barking: 4,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Diabetes", "Eye disorders", "Heart problems"],
    blurb: "An adaptable, friendly, gentle smiling Siberian — bred by nomadic Samoyed people to herd reindeer.",
    temperament: ["Adaptable", "Friendly", "Gentle"],
  },
  {
    slug: "akita",
    name: "Akita",
    group: "working",
    size: "large",
    origin: "Japan",
    heightMaleMin: 26, heightMaleMax: 28, heightFemaleMin: 24, heightFemaleMax: 26,
    weightMaleMin: 100, weightMaleMax: 130, weightFemaleMin: 70, weightFemaleMax: 100,
    lifespanMin: 10, lifespanMax: 14,
    energy: 3, trainability: 3, shedding: 4, grooming: 2, barking: 2,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 2,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Eye disorders", "Hypothyroidism"],
    blurb: "A courageous, dignified, profoundly loyal Japanese guardian — one breed, one master philosophy.",
    temperament: ["Courageous", "Dignified", "Profoundly Loyal"],
  },
  {
    slug: "shiba-inu",
    name: "Shiba Inu",
    group: "non-sporting",
    size: "small",
    origin: "Japan",
    heightMaleMin: 14.5, heightMaleMax: 16.5, heightFemaleMin: 13.5, heightFemaleMax: 15.5,
    weightMaleMin: 23, weightMaleMax: 23, weightFemaleMin: 17, weightFemaleMax: 17,
    lifespanMin: 13, lifespanMax: 16,
    energy: 4, trainability: 2, shedding: 4, grooming: 2, barking: 2,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Hip dysplasia", "Eye disorders", "Allergies"],
    blurb: "An alert, active, attentive small Spitz — Japan's most popular national dog and the original 'doge' meme.",
    temperament: ["Alert", "Active", "Attentive"],
  },
  {
    slug: "bull-terrier",
    name: "Bull Terrier",
    group: "terrier",
    size: "medium",
    origin: "England",
    heightMaleMin: 21, heightMaleMax: 22, heightFemaleMin: 21, heightFemaleMax: 22,
    weightMaleMin: 50, weightMaleMax: 70, weightFemaleMin: 50, weightFemaleMax: 70,
    lifespanMin: 12, lifespanMax: 13,
    energy: 4, trainability: 3, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Deafness", "Heart disease", "Skin issues", "Kidney problems"],
    blurb: "A playful, charming, mischievous egg-headed gladiator — Spuds MacKenzie, the original Target dog.",
    temperament: ["Playful", "Charming", "Mischievous"],
  },
  {
    slug: "staffordshire-bull-terrier",
    name: "Staffordshire Bull Terrier",
    group: "terrier",
    size: "medium",
    origin: "England",
    heightMaleMin: 14, heightMaleMax: 16, heightFemaleMin: 14, heightFemaleMax: 16,
    weightMaleMin: 28, weightMaleMax: 38, weightFemaleMin: 24, weightFemaleMax: 34,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 5, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye conditions", "Skin allergies", "Patellar luxation"],
    blurb: "A clever, brave, tenacious bull-and-terrier — UK's beloved 'Staffy', famously gentle with kids.",
    temperament: ["Clever", "Brave", "Tenacious"],
  },
  {
    slug: "american-staffordshire-terrier",
    name: "American Staffordshire Terrier",
    group: "terrier",
    size: "medium",
    origin: "USA",
    heightMaleMin: 18, heightMaleMax: 19, heightFemaleMin: 17, heightFemaleMax: 18,
    weightMaleMin: 55, weightMaleMax: 70, weightFemaleMin: 40, weightFemaleMax: 55,
    lifespanMin: 12, lifespanMax: 16,
    energy: 4, trainability: 4, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 4, goodWithDogs: 2, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Heart disease", "Skin allergies", "Cerebellar ataxia"],
    blurb: "A confident, smart, good-natured terrier — the AmStaff, larger cousin of the Staffy.",
    temperament: ["Confident", "Smart", "Good-Natured"],
  },
  {
    slug: "scottish-terrier",
    name: "Scottish Terrier",
    group: "terrier",
    size: "small",
    origin: "Scotland",
    heightMaleMin: 10, heightMaleMax: 10, heightFemaleMin: 10, heightFemaleMax: 10,
    weightMaleMin: 19, weightMaleMax: 22, weightFemaleMin: 18, weightFemaleMax: 21,
    lifespanMin: 12, lifespanMax: 15,
    energy: 3, trainability: 3, shedding: 1, grooming: 4, barking: 4,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Scotty cramp", "Von Willebrand's disease", "Bladder cancer"],
    blurb: "An independent, confident, spirited terrier from the Scottish Highlands — the original 'Scottie'.",
    temperament: ["Confident", "Independent", "Spirited"],
  },
  {
    slug: "west-highland-white-terrier",
    name: "West Highland White Terrier",
    group: "terrier",
    size: "small",
    origin: "Scotland",
    heightMaleMin: 11, heightMaleMax: 11, heightFemaleMin: 10, heightFemaleMax: 10,
    weightMaleMin: 15, weightMaleMax: 20, weightFemaleMin: 15, weightFemaleMax: 20,
    lifespanMin: 13, lifespanMax: 15,
    energy: 4, trainability: 3, shedding: 2, grooming: 4, barking: 4,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Skin allergies", "Hip dysplasia", "Cataracts", "Liver disease"],
    blurb: "A loyal, happy, entertaining little terrier — the iconic Cesar dog food face with a snowy coat.",
    temperament: ["Loyal", "Happy", "Entertaining"],
  },
  {
    slug: "jack-russell-terrier",
    name: "Jack Russell Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 10, heightMaleMax: 15, heightFemaleMin: 10, heightFemaleMax: 15,
    weightMaleMin: 13, weightMaleMax: 17, weightFemaleMin: 13, weightFemaleMax: 17,
    lifespanMin: 13, lifespanMax: 18,
    energy: 5, trainability: 3, shedding: 3, grooming: 2, barking: 5,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Eye disorders", "Deafness"],
    blurb: "A fearless, vocal, athletic small fox terrier — Eddie from Frasier, ten pounds of pure energy.",
    temperament: ["Fearless", "Vocal", "Athletic"],
  },
  {
    slug: "airedale-terrier",
    name: "Airedale Terrier",
    group: "terrier",
    size: "large",
    origin: "England",
    heightMaleMin: 23, heightMaleMax: 23, heightFemaleMin: 22, heightFemaleMax: 22,
    weightMaleMin: 50, weightMaleMax: 70, weightFemaleMin: 40, weightFemaleMax: 55,
    lifespanMin: 11, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Hypothyroidism", "Skin issues"],
    blurb: "A friendly, clever, courageous 'King of Terriers' — the largest of the terrier clan from Yorkshire.",
    temperament: ["Friendly", "Clever", "Courageous"],
  },
  {
    slug: "wire-fox-terrier",
    name: "Wire Fox Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 15, heightMaleMax: 15, heightFemaleMin: 15, heightFemaleMax: 15,
    weightMaleMin: 17, weightMaleMax: 19, weightFemaleMin: 15, weightFemaleMax: 17,
    lifespanMin: 12, lifespanMax: 15,
    energy: 5, trainability: 4, shedding: 1, grooming: 4, barking: 4,
    goodWithKids: 4, goodWithDogs: 2, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Eye disorders", "Hypothyroidism"],
    blurb: "A confident, alert, gregarious fox-bolter — high-spirited British show ring star with a wiry white coat.",
    temperament: ["Confident", "Alert", "Gregarious"],
  },
];
