import type { Breed } from "./types";

// Part 6: Doodles, designer mixes, more variety
export const BREEDS_PART6: Breed[] = [
  {
    slug: "goldendoodle",
    name: "Goldendoodle",
    group: "miscellaneous",
    size: "large",
    origin: "USA",
    heightMaleMin: 20, heightMaleMax: 24, heightFemaleMin: 20, heightFemaleMax: 24,
    weightMaleMin: 50, weightMaleMax: 90, weightFemaleMin: 50, weightFemaleMax: 90,
    lifespanMin: 10, lifespanMax: 15,
    energy: 4, trainability: 5, shedding: 2, grooming: 4, barking: 2,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 4, intelligence: 5, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Heart conditions", "Eye disorders", "Allergies"],
    blurb: "A friendly, smart, family-oriented Golden Retriever × Poodle hybrid — top US designer dog of the 2020s.",
    temperament: ["Friendly", "Smart", "Family-Oriented"],
  },
  {
    slug: "labradoodle",
    name: "Labradoodle",
    group: "miscellaneous",
    size: "large",
    origin: "Australia",
    heightMaleMin: 21, heightMaleMax: 24, heightFemaleMin: 21, heightFemaleMax: 24,
    weightMaleMin: 50, weightMaleMax: 65, weightFemaleMin: 50, weightFemaleMax: 65,
    lifespanMin: 12, lifespanMax: 14,
    energy: 5, trainability: 5, shedding: 2, grooming: 4, barking: 2,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 4, intelligence: 5, exerciseNeeds: 5, droolingLevel: 2,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Allergies"],
    blurb: "A friendly, energetic, intelligent Labrador × Poodle hybrid — the original 'doodle' bred for service work.",
    temperament: ["Friendly", "Energetic", "Intelligent"],
  },
  {
    slug: "cockapoo",
    name: "Cockapoo",
    group: "miscellaneous",
    size: "small",
    origin: "USA",
    heightMaleMin: 10, heightMaleMax: 15, heightFemaleMin: 10, heightFemaleMax: 15,
    weightMaleMin: 12, weightMaleMax: 24, weightFemaleMin: 12, weightFemaleMax: 24,
    lifespanMin: 13, lifespanMax: 16,
    energy: 4, trainability: 4, shedding: 2, grooming: 4, barking: 2,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Ear infections", "Eye disorders", "Hip dysplasia"],
    blurb: "A people-loving, intelligent, low-shed Cocker Spaniel × Poodle hybrid — smaller doodle, apartment-sized.",
    temperament: ["People-Loving", "Intelligent", "Easygoing"],
  },
  {
    slug: "maltipoo",
    name: "Maltipoo",
    group: "miscellaneous",
    size: "toy",
    origin: "USA",
    heightMaleMin: 8, heightMaleMax: 14, heightFemaleMin: 8, heightFemaleMax: 14,
    weightMaleMin: 5, weightMaleMax: 20, weightFemaleMin: 5, weightFemaleMax: 20,
    lifespanMin: 10, lifespanMax: 13,
    energy: 3, trainability: 4, shedding: 1, grooming: 4, barking: 4,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "White shaker syndrome", "Eye disorders"],
    blurb: "A gentle, affectionate, lively Maltese × Poodle hybrid — popular small hypoallergenic apartment companion.",
    temperament: ["Gentle", "Affectionate", "Lively"],
  },
  {
    slug: "yorkipoo",
    name: "Yorkipoo",
    group: "miscellaneous",
    size: "toy",
    origin: "USA",
    heightMaleMin: 7, heightMaleMax: 15, heightFemaleMin: 7, heightFemaleMax: 15,
    weightMaleMin: 3, weightMaleMax: 14, weightFemaleMin: 3, weightFemaleMax: 14,
    lifespanMin: 10, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 4,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Tracheal collapse", "Dental issues"],
    blurb: "A confident, energetic, affectionate Yorkshire × Poodle hybrid — pocket-sized hypoallergenic spitfire.",
    temperament: ["Confident", "Energetic", "Affectionate"],
  },
  {
    slug: "puggle",
    name: "Puggle",
    group: "miscellaneous",
    size: "small",
    origin: "USA",
    heightMaleMin: 13, heightMaleMax: 15, heightFemaleMin: 13, heightFemaleMax: 15,
    weightMaleMin: 18, weightMaleMax: 30, weightFemaleMin: 18, weightFemaleMax: 30,
    lifespanMin: 10, lifespanMax: 15,
    energy: 4, trainability: 3, shedding: 4, grooming: 2, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Patellar luxation", "Brachycephalic syndrome", "Eye disorders"],
    blurb: "A friendly, sociable, playful Pug × Beagle hybrid — pug face, beagle personality, perfect city dog.",
    temperament: ["Friendly", "Sociable", "Playful"],
  },
  {
    slug: "schnoodle",
    name: "Schnoodle",
    group: "miscellaneous",
    size: "medium",
    origin: "USA",
    heightMaleMin: 10, heightMaleMax: 26, heightFemaleMin: 10, heightFemaleMax: 26,
    weightMaleMin: 6, weightMaleMax: 75, weightFemaleMin: 6, weightFemaleMax: 75,
    lifespanMin: 10, lifespanMax: 16,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Skin conditions"],
    blurb: "A playful, smart, family-oriented Schnauzer × Poodle hybrid — comes in mini, standard, and giant.",
    temperament: ["Playful", "Smart", "Family-Oriented"],
  },
  {
    slug: "morkie",
    name: "Morkie",
    group: "miscellaneous",
    size: "toy",
    origin: "USA",
    heightMaleMin: 4, heightMaleMax: 8, heightFemaleMin: 4, heightFemaleMax: 8,
    weightMaleMin: 4, weightMaleMax: 8, weightFemaleMin: 4, weightFemaleMax: 8,
    lifespanMin: 10, lifespanMax: 13,
    energy: 4, trainability: 3, shedding: 1, grooming: 4, barking: 5,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Tracheal collapse", "Hypoglycemia"],
    blurb: "A spunky, affectionate, confident Maltese × Yorkie hybrid — pint-size companion with big personality.",
    temperament: ["Spunky", "Affectionate", "Confident"],
  },
  {
    slug: "chiweenie",
    name: "Chiweenie",
    group: "miscellaneous",
    size: "toy",
    origin: "USA",
    heightMaleMin: 6, heightMaleMax: 10, heightFemaleMin: 6, heightFemaleMax: 10,
    weightMaleMin: 5, weightMaleMax: 12, weightFemaleMin: 5, weightFemaleMax: 12,
    lifespanMin: 13, lifespanMax: 16,
    energy: 4, trainability: 3, shedding: 3, grooming: 2, barking: 4,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["IVDD", "Patellar luxation", "Hypoglycemia", "Dental issues"],
    blurb: "A spirited, devoted, big-personality Chihuahua × Dachshund hybrid — toy-sized 'mexican hot dog'.",
    temperament: ["Spirited", "Devoted", "Lively"],
  },
  {
    slug: "pomsky",
    name: "Pomsky",
    group: "miscellaneous",
    size: "small",
    origin: "USA",
    heightMaleMin: 10, heightMaleMax: 15, heightFemaleMin: 10, heightFemaleMax: 15,
    weightMaleMin: 20, weightMaleMax: 30, weightFemaleMin: 20, weightFemaleMax: 30,
    lifespanMin: 13, lifespanMax: 15,
    energy: 5, trainability: 3, shedding: 4, grooming: 3, barking: 4,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Skin allergies"],
    blurb: "An energetic, playful, intelligent Pomeranian × Husky hybrid — Husky's fluff in a Pomeranian frame.",
    temperament: ["Energetic", "Playful", "Intelligent"],
  },
  {
    slug: "australian-kelpie",
    name: "Australian Kelpie",
    group: "herding",
    size: "medium",
    origin: "Australia",
    heightMaleMin: 17, heightMaleMax: 20, heightFemaleMin: 15, heightFemaleMax: 18,
    weightMaleMin: 35, weightMaleMax: 50, weightFemaleMin: 30, weightFemaleMax: 45,
    lifespanMin: 12, lifespanMax: 15,
    energy: 5, trainability: 5, shedding: 3, grooming: 1, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 2, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Cerebellar abiotrophy", "Cryptorchidism"],
    blurb: "A clever, devoted, energetic Australian sheep musterer — outback workaholic with an off-switch problem.",
    temperament: ["Clever", "Devoted", "Energetic"],
  },
  {
    slug: "australian-stumpy-tail-cattle-dog",
    name: "Australian Stumpy Tail Cattle Dog",
    group: "herding",
    size: "medium",
    origin: "Australia",
    heightMaleMin: 18, heightMaleMax: 20, heightFemaleMin: 17, heightFemaleMax: 19,
    weightMaleMin: 35, weightMaleMax: 50, weightFemaleMin: 35, weightFemaleMax: 50,
    lifespanMin: 12, lifespanMax: 15,
    energy: 5, trainability: 4, shedding: 3, grooming: 1, barking: 3,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 2, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Deafness", "Eye disorders"],
    blurb: "An alert, hardy, watchful Australian drover — cousin to the Cattle Dog with a naturally bobbed tail.",
    temperament: ["Alert", "Hardy", "Watchful"],
  },
  {
    slug: "icelandic-sheepdog",
    name: "Icelandic Sheepdog",
    group: "herding",
    size: "medium",
    origin: "Iceland",
    heightMaleMin: 17.5, heightMaleMax: 18, heightFemaleMin: 16.5, heightFemaleMax: 17,
    weightMaleMin: 25, weightMaleMax: 30, weightFemaleMin: 25, weightFemaleMax: 30,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 4, grooming: 3, barking: 4,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Patellar luxation", "Eye disorders"],
    blurb: "A friendly, hardy, herding Spitz from Iceland — the country's only native breed, brought by Vikings.",
    temperament: ["Friendly", "Hardy", "Cheerful"],
  },
  {
    slug: "swedish-vallhund",
    name: "Swedish Vallhund",
    group: "herding",
    size: "small",
    origin: "Sweden",
    heightMaleMin: 12.5, heightMaleMax: 13.75, heightFemaleMin: 11.5, heightFemaleMax: 12.75,
    weightMaleMin: 20, weightMaleMax: 35, weightFemaleMin: 20, weightFemaleMax: 35,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 4, grooming: 2, barking: 4,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders"],
    blurb: "A friendly, energetic, watchful Viking Spitz — Sweden's 'Wolf Dog of the Vikings', resembles a Corgi.",
    temperament: ["Friendly", "Energetic", "Watchful"],
  },
  {
    slug: "polish-lowland-sheepdog",
    name: "Polish Lowland Sheepdog",
    group: "herding",
    size: "medium",
    origin: "Poland",
    heightMaleMin: 18, heightMaleMax: 20, heightFemaleMin: 17, heightFemaleMax: 19,
    weightMaleMin: 30, weightMaleMax: 50, weightFemaleMin: 30, weightFemaleMax: 50,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 1, grooming: 5, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders"],
    blurb: "A clever, lively, perceptive Polish shaggy herder — shaggy-coated dog known for memory and adaptability.",
    temperament: ["Clever", "Lively", "Perceptive"],
  },
  {
    slug: "spanish-water-dog",
    name: "Spanish Water Dog",
    group: "herding",
    size: "medium",
    origin: "Spain",
    heightMaleMin: 17.5, heightMaleMax: 19.75, heightFemaleMin: 15.75, heightFemaleMax: 18,
    weightMaleMin: 40, weightMaleMax: 49, weightFemaleMin: 31, weightFemaleMax: 40,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 3, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Hypothyroidism"],
    blurb: "A loyal, smart, athletic Spanish all-purpose herder, hunter, and water-rescuer with a curly cord coat.",
    temperament: ["Loyal", "Smart", "Athletic"],
  },
  {
    slug: "portuguese-water-dog",
    name: "Portuguese Water Dog",
    group: "working",
    size: "medium",
    origin: "Portugal",
    heightMaleMin: 20, heightMaleMax: 23, heightFemaleMin: 17, heightFemaleMax: 21,
    weightMaleMin: 42, weightMaleMax: 60, weightFemaleMin: 35, weightFemaleMax: 50,
    lifespanMin: 11, lifespanMax: 13,
    energy: 4, trainability: 5, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 3, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Storage diseases"],
    blurb: "An affectionate, athletic, smart fisherman's dog — Bo Obama's breed, swims and herds fish into nets.",
    temperament: ["Affectionate", "Athletic", "Smart"],
  },
  {
    slug: "irish-water-spaniel",
    name: "Irish Water Spaniel",
    group: "sporting",
    size: "large",
    origin: "Ireland",
    heightMaleMin: 22, heightMaleMax: 24, heightFemaleMin: 21, heightFemaleMax: 23,
    weightMaleMin: 55, weightMaleMax: 68, weightFemaleMin: 45, weightFemaleMax: 58,
    lifespanMin: 12, lifespanMax: 13,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Hypothyroidism"],
    blurb: "A playful, hardworking, brave water retriever — Ireland's sporting clown with a famous rat-tail.",
    temperament: ["Playful", "Hardworking", "Brave"],
  },
  {
    slug: "american-water-spaniel",
    name: "American Water Spaniel",
    group: "sporting",
    size: "medium",
    origin: "USA",
    heightMaleMin: 15, heightMaleMax: 18, heightFemaleMin: 15, heightFemaleMax: 18,
    weightMaleMin: 30, weightMaleMax: 45, weightFemaleMin: 25, weightFemaleMax: 40,
    lifespanMin: 10, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 2, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Cardiac problems"],
    blurb: "An eager, charming, energetic Wisconsin water retriever — state dog, bred for icy duck hunts.",
    temperament: ["Eager", "Charming", "Energetic"],
  },
  {
    slug: "field-spaniel",
    name: "Field Spaniel",
    group: "sporting",
    size: "medium",
    origin: "England",
    heightMaleMin: 18, heightMaleMax: 18, heightFemaleMin: 17, heightFemaleMax: 17,
    weightMaleMin: 35, weightMaleMax: 50, weightFemaleMin: 35, weightFemaleMax: 50,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 3, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Ear infections"],
    blurb: "A sensitive, fun-loving, affectionate British spaniel — rare flushing breed, taller than a Cocker.",
    temperament: ["Sensitive", "Fun-Loving", "Affectionate"],
  },
];
