import type { Breed } from "./types";

// Part 4: More herding, working, and unique breeds
export const BREEDS_PART4: Breed[] = [
  {
    slug: "old-english-sheepdog",
    name: "Old English Sheepdog",
    group: "herding",
    size: "large",
    origin: "England",
    heightMaleMin: 22, heightMaleMax: 24, heightFemaleMin: 21, heightFemaleMax: 23,
    weightMaleMin: 60, weightMaleMax: 100, weightFemaleMin: 60, weightFemaleMax: 100,
    lifespanMin: 10, lifespanMax: 12,
    energy: 3, trainability: 4, shedding: 4, grooming: 5, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 2,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Cataracts", "Hypothyroidism", "Deafness"],
    blurb: "An adaptable, smart, gentle drover from western England — the shaggy 'Dulux dog' with hidden eyes.",
    temperament: ["Adaptable", "Smart", "Gentle"],
  },
  {
    slug: "collie",
    name: "Collie (Rough)",
    group: "herding",
    size: "large",
    origin: "Scotland",
    heightMaleMin: 24, heightMaleMax: 26, heightFemaleMin: 22, heightFemaleMax: 24,
    weightMaleMin: 60, weightMaleMax: 75, weightFemaleMin: 50, weightFemaleMax: 65,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 5, shedding: 4, grooming: 4, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Collie eye anomaly", "MDR1 gene mutation", "Hip dysplasia"],
    blurb: "A devoted, graceful, proud Scottish herder — Lassie, the world's most famous fictional dog.",
    temperament: ["Devoted", "Graceful", "Proud"],
  },
  {
    slug: "belgian-malinois",
    name: "Belgian Malinois",
    group: "herding",
    size: "large",
    origin: "Belgium",
    heightMaleMin: 24, heightMaleMax: 26, heightFemaleMin: 22, heightFemaleMax: 24,
    weightMaleMin: 60, weightMaleMax: 80, weightFemaleMin: 40, weightFemaleMax: 60,
    lifespanMin: 14, lifespanMax: 16,
    energy: 5, trainability: 5, shedding: 3, grooming: 2, barking: 3,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 2, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Elbow dysplasia", "Eye problems"],
    blurb: "A confident, smart, hard-working Belgian shepherd — top choice for Navy SEAL military units worldwide.",
    temperament: ["Confident", "Smart", "Hardworking"],
  },
  {
    slug: "cardigan-welsh-corgi",
    name: "Cardigan Welsh Corgi",
    group: "herding",
    size: "small",
    origin: "Wales",
    heightMaleMin: 10.5, heightMaleMax: 12.5, heightFemaleMin: 10.5, heightFemaleMax: 12.5,
    weightMaleMin: 30, weightMaleMax: 38, weightFemaleMin: 25, weightFemaleMax: 34,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 3, grooming: 2, barking: 3,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "IVDD", "Eye disorders"],
    blurb: "A loyal, smart, affectionate herding dwarf with a long tail — Pembroke's older, mellower cousin.",
    temperament: ["Loyal", "Smart", "Affectionate"],
  },
  {
    slug: "miniature-poodle",
    name: "Miniature Poodle",
    group: "non-sporting",
    size: "small",
    origin: "Germany",
    heightMaleMin: 11, heightMaleMax: 15, heightFemaleMin: 11, heightFemaleMax: 15,
    weightMaleMin: 10, weightMaleMax: 15, weightFemaleMin: 10, weightFemaleMax: 15,
    lifespanMin: 10, lifespanMax: 18,
    energy: 4, trainability: 5, shedding: 1, grooming: 5, barking: 3,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 5, intelligence: 5, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Eye disorders", "Epilepsy", "Legg-Calve-Perthes"],
    blurb: "An active, proud, very smart smaller version of the Standard Poodle — circus star of yesteryear.",
    temperament: ["Active", "Proud", "Very Smart"],
  },
  {
    slug: "toy-poodle",
    name: "Toy Poodle",
    group: "toy",
    size: "toy",
    origin: "Germany",
    heightMaleMin: 9, heightMaleMax: 10, heightFemaleMin: 9, heightFemaleMax: 10,
    weightMaleMin: 4, weightMaleMax: 6, weightFemaleMin: 4, weightFemaleMax: 6,
    lifespanMin: 10, lifespanMax: 18,
    energy: 4, trainability: 5, shedding: 1, grooming: 5, barking: 3,
    goodWithKids: 3, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 5, intelligence: 5, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Tracheal collapse", "Eye disorders", "Dental issues"],
    blurb: "An active, intelligent, lively toy version of the Poodle — apartment-friendly hypoallergenic charmer.",
    temperament: ["Active", "Intelligent", "Lively"],
  },
  {
    slug: "english-bulldog",
    name: "English Bulldog",
    group: "non-sporting",
    size: "medium",
    origin: "England",
    heightMaleMin: 14, heightMaleMax: 15, heightFemaleMin: 14, heightFemaleMax: 15,
    weightMaleMin: 50, weightMaleMax: 50, weightFemaleMin: 40, weightFemaleMax: 40,
    lifespanMin: 8, lifespanMax: 10,
    energy: 2, trainability: 2, shedding: 3, grooming: 2, barking: 1,
    goodWithKids: 5, goodWithDogs: 3, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 3, exerciseNeeds: 2, droolingLevel: 4,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Brachycephalic syndrome", "Hip dysplasia", "Skin fold dermatitis"],
    blurb: "A calm, courageous, friendly English breed — wrinkly-faced, jowly mascot of universities and the Marines.",
    temperament: ["Calm", "Courageous", "Friendly"],
  },
  {
    slug: "american-bulldog",
    name: "American Bulldog",
    group: "working",
    size: "large",
    origin: "USA",
    heightMaleMin: 22, heightMaleMax: 25, heightFemaleMin: 20, heightFemaleMax: 23,
    weightMaleMin: 75, weightMaleMax: 100, weightFemaleMin: 60, weightFemaleMax: 80,
    lifespanMin: 10, lifespanMax: 12,
    energy: 4, trainability: 4, shedding: 3, grooming: 1, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 5,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 3,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Cherry eye", "Skin allergies", "Kidney disease"],
    blurb: "A loyal, athletic, hard-working farm guardian — taller and more athletic than the English Bulldog.",
    temperament: ["Loyal", "Athletic", "Hardworking"],
  },
  {
    slug: "dalmatian",
    name: "Dalmatian",
    group: "non-sporting",
    size: "medium",
    origin: "Croatia",
    heightMaleMin: 19, heightMaleMax: 24, heightFemaleMin: 19, heightFemaleMax: 24,
    weightMaleMin: 45, weightMaleMax: 70, weightFemaleMin: 45, weightFemaleMax: 70,
    lifespanMin: 11, lifespanMax: 13,
    energy: 5, trainability: 4, shedding: 4, grooming: 2, barking: 2,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Deafness", "Urinary stones", "Hip dysplasia", "Skin allergies"],
    blurb: "A dignified, smart, outgoing spotted coach dog — 101 Dalmatians, original carriage and firehouse dog.",
    temperament: ["Dignified", "Smart", "Outgoing"],
  },
  {
    slug: "chow-chow",
    name: "Chow Chow",
    group: "non-sporting",
    size: "medium",
    origin: "China",
    heightMaleMin: 17, heightMaleMax: 20, heightFemaleMin: 17, heightFemaleMax: 20,
    weightMaleMin: 45, weightMaleMax: 70, weightFemaleMin: 45, weightFemaleMax: 70,
    lifespanMin: 8, lifespanMax: 12,
    energy: 2, trainability: 2, shedding: 3, grooming: 4, barking: 1,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 3, intelligence: 4, exerciseNeeds: 2, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Skin issues", "Bloat"],
    blurb: "A dignified, bright, serious-minded ancient Chinese breed with a famous purple-blue tongue.",
    temperament: ["Dignified", "Bright", "Serious-Minded"],
  },
  {
    slug: "shar-pei",
    name: "Chinese Shar-Pei",
    group: "non-sporting",
    size: "medium",
    origin: "China",
    heightMaleMin: 18, heightMaleMax: 20, heightFemaleMin: 18, heightFemaleMax: 20,
    weightMaleMin: 45, weightMaleMax: 60, weightFemaleMin: 45, weightFemaleMax: 60,
    lifespanMin: 8, lifespanMax: 12,
    energy: 3, trainability: 3, shedding: 2, grooming: 1, barking: 2,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye problems", "Skin issues", "Allergies"],
    blurb: "A loyal, calm, independent wrinkly Chinese guardian — hippopotamus-faced ancient farm and palace dog.",
    temperament: ["Loyal", "Calm", "Independent"],
  },
  {
    slug: "keeshond",
    name: "Keeshond",
    group: "non-sporting",
    size: "medium",
    origin: "Netherlands",
    heightMaleMin: 18, heightMaleMax: 18, heightFemaleMin: 17, heightFemaleMax: 17,
    weightMaleMin: 35, weightMaleMax: 45, weightFemaleMin: 35, weightFemaleMax: 45,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 5, grooming: 3, barking: 4,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Heart issues", "Epilepsy"],
    blurb: "A friendly, lively, outgoing Dutch barge dog — Holland's national dog with a fluffy 'spectacles' face.",
    temperament: ["Friendly", "Lively", "Outgoing"],
  },
  {
    slug: "tibetan-mastiff",
    name: "Tibetan Mastiff",
    group: "working",
    size: "giant",
    origin: "Tibet",
    heightMaleMin: 26, heightMaleMax: 26, heightFemaleMin: 24, heightFemaleMax: 24,
    weightMaleMin: 90, weightMaleMax: 150, weightFemaleMin: 70, weightFemaleMax: 120,
    lifespanMin: 10, lifespanMax: 12,
    energy: 2, trainability: 2, shedding: 4, grooming: 3, barking: 4,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 1, protectiveness: 5,
    adaptability: 2, intelligence: 4, exerciseNeeds: 3, droolingLevel: 3,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Hypothyroidism", "Eye disorders"],
    blurb: "An aloof, intelligent, ancient Himalayan livestock guardian — the lion-maned protector of monasteries.",
    temperament: ["Aloof", "Intelligent", "Independent"],
  },
  {
    slug: "leonberger",
    name: "Leonberger",
    group: "working",
    size: "giant",
    origin: "Germany",
    heightMaleMin: 28, heightMaleMax: 31.5, heightFemaleMin: 25.5, heightFemaleMax: 29.5,
    weightMaleMin: 110, weightMaleMax: 170, weightFemaleMin: 90, weightFemaleMax: 140,
    lifespanMin: 7, lifespanMax: 10,
    energy: 3, trainability: 4, shedding: 5, grooming: 4, barking: 2,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 4,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bone cancer", "Bloat", "Polyneuropathy"],
    blurb: "A friendly, gentle, playful giant — bred to resemble a lion, with a famous black-masked golden mane.",
    temperament: ["Friendly", "Gentle", "Playful"],
  },
  {
    slug: "anatolian-shepherd",
    name: "Anatolian Shepherd",
    group: "working",
    size: "giant",
    origin: "Turkey",
    heightMaleMin: 29, heightMaleMax: 29, heightFemaleMin: 27, heightFemaleMax: 27,
    weightMaleMin: 110, weightMaleMax: 150, weightFemaleMin: 80, weightFemaleMax: 120,
    lifespanMin: 11, lifespanMax: 13,
    energy: 3, trainability: 3, shedding: 4, grooming: 2, barking: 3,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 2, intelligence: 4, exerciseNeeds: 3, droolingLevel: 2,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Hypothyroidism", "Bloat"],
    blurb: "A loyal, independent, reserved livestock guardian from Turkey — works alone protecting flocks from wolves.",
    temperament: ["Loyal", "Independent", "Reserved"],
  },
  {
    slug: "kuvasz",
    name: "Kuvasz",
    group: "working",
    size: "large",
    origin: "Hungary",
    heightMaleMin: 28, heightMaleMax: 30, heightFemaleMin: 26, heightFemaleMax: 28,
    weightMaleMin: 100, weightMaleMax: 115, weightFemaleMin: 70, weightFemaleMax: 90,
    lifespanMin: 10, lifespanMax: 12,
    energy: 4, trainability: 3, shedding: 4, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 2, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Osteochondritis dissecans"],
    blurb: "A loyal, courageous, fearless white Hungarian guardian — flock protector with double-thick weather coat.",
    temperament: ["Loyal", "Courageous", "Fearless"],
  },
  {
    slug: "komondor",
    name: "Komondor",
    group: "working",
    size: "giant",
    origin: "Hungary",
    heightMaleMin: 27.5, heightMaleMax: 27.5, heightFemaleMin: 25.5, heightFemaleMax: 25.5,
    weightMaleMin: 100, weightMaleMax: 100, weightFemaleMin: 80, weightFemaleMax: 80,
    lifespanMin: 10, lifespanMax: 12,
    energy: 3, trainability: 3, shedding: 1, grooming: 5, barking: 4,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 2, intelligence: 4, exerciseNeeds: 3, droolingLevel: 2,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Eye problems", "Skin issues"],
    blurb: "A serious, loyal, dignified giant Hungarian guardian — the famous corded 'mop dog' that camouflages with sheep.",
    temperament: ["Serious", "Loyal", "Dignified"],
  },
  {
    slug: "puli",
    name: "Puli",
    group: "herding",
    size: "medium",
    origin: "Hungary",
    heightMaleMin: 17, heightMaleMax: 17, heightFemaleMin: 16, heightFemaleMax: 16,
    weightMaleMin: 25, weightMaleMax: 35, weightFemaleMin: 25, weightFemaleMax: 35,
    lifespanMin: 10, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 1, grooming: 5, barking: 4,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Hearing problems"],
    blurb: "A loyal, smart, energetic Hungarian sheepdog with corded dreadlock coat — agile and acrobatic.",
    temperament: ["Loyal", "Smart", "Energetic"],
  },
  {
    slug: "norwegian-elkhound",
    name: "Norwegian Elkhound",
    group: "hound",
    size: "medium",
    origin: "Norway",
    heightMaleMin: 19.5, heightMaleMax: 20.5, heightFemaleMin: 18, heightFemaleMax: 19,
    weightMaleMin: 55, weightMaleMax: 55, weightFemaleMin: 48, weightFemaleMax: 48,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 3, shedding: 4, grooming: 2, barking: 4,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Progressive retinal atrophy", "Hypothyroidism"],
    blurb: "A friendly, dignified, confident Viking elk-hunting Spitz — Norway's national breed for over 6,000 years.",
    temperament: ["Friendly", "Dignified", "Confident"],
  },
  {
    slug: "finnish-spitz",
    name: "Finnish Spitz",
    group: "non-sporting",
    size: "medium",
    origin: "Finland",
    heightMaleMin: 17.5, heightMaleMax: 20, heightFemaleMin: 15.5, heightFemaleMax: 18,
    weightMaleMin: 25, weightMaleMax: 33, weightFemaleMin: 20, weightFemaleMax: 28,
    lifespanMin: 13, lifespanMax: 15,
    energy: 4, trainability: 3, shedding: 3, grooming: 2, barking: 5,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Patellar luxation", "Epilepsy"],
    blurb: "A friendly, faithful, alert fox-red Finnish bark-pointer — national dog of Finland, hunts by yodeling.",
    temperament: ["Friendly", "Faithful", "Alert"],
  },
  {
    slug: "schipperke",
    name: "Schipperke",
    group: "non-sporting",
    size: "small",
    origin: "Belgium",
    heightMaleMin: 11, heightMaleMax: 13, heightFemaleMin: 10, heightFemaleMax: 12,
    weightMaleMin: 10, weightMaleMax: 16, weightFemaleMin: 10, weightFemaleMax: 16,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 3, grooming: 2, barking: 4,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["MPS IIIB", "Patellar luxation", "Hypothyroidism"],
    blurb: "A confident, alert, curious Belgian barge dog — small black 'little captain' with foxy face and ruff.",
    temperament: ["Confident", "Alert", "Curious"],
  },
];
