import type { Breed } from "./types";

// Part 1: Most popular breeds (AKC top 50 by registration)
export const BREEDS_PART1: Breed[] = [
  {
    slug: "labrador-retriever",
    name: "Labrador Retriever",
    group: "sporting",
    size: "large",
    origin: "Canada",
    heightMaleMin: 22.5, heightMaleMax: 24.5, heightFemaleMin: 21.5, heightFemaleMax: 23.5,
    weightMaleMin: 65, weightMaleMax: 80, weightFemaleMin: 55, weightFemaleMax: 70,
    lifespanMin: 11, lifespanMax: 13,
    energy: 5, trainability: 5, shedding: 4, grooming: 2, barking: 3,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 4, intelligence: 5, exerciseNeeds: 5, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Elbow dysplasia", "Obesity", "Progressive retinal atrophy"],
    blurb: "America's most popular dog — a friendly, outgoing, athletic retriever bred to fetch waterfowl.",
    temperament: ["Friendly", "Active", "Outgoing", "Even-Tempered"],
  },
  {
    slug: "french-bulldog",
    name: "French Bulldog",
    group: "non-sporting",
    size: "small",
    origin: "France",
    heightMaleMin: 11, heightMaleMax: 13, heightFemaleMin: 11, heightFemaleMax: 13,
    weightMaleMin: 20, weightMaleMax: 28, weightFemaleMin: 16, weightFemaleMax: 24,
    lifespanMin: 10, lifespanMax: 12,
    energy: 2, trainability: 3, shedding: 3, grooming: 2, barking: 1,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 5, intelligence: 3, exerciseNeeds: 2, droolingLevel: 3,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Brachycephalic syndrome", "Hip dysplasia", "Allergies", "IVDD"],
    blurb: "A compact, muscular, bat-eared companion bred for city living and apartment life.",
    temperament: ["Adaptable", "Playful", "Smart"],
  },
  {
    slug: "golden-retriever",
    name: "Golden Retriever",
    group: "sporting",
    size: "large",
    origin: "Scotland",
    heightMaleMin: 23, heightMaleMax: 24, heightFemaleMin: 21.5, heightFemaleMax: 22.5,
    weightMaleMin: 65, weightMaleMax: 75, weightFemaleMin: 55, weightFemaleMax: 65,
    lifespanMin: 10, lifespanMax: 12,
    energy: 5, trainability: 5, shedding: 5, grooming: 3, barking: 2,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 4, intelligence: 5, exerciseNeeds: 5, droolingLevel: 2,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Cancer", "Hip dysplasia", "Heart disease", "Skin conditions"],
    blurb: "A friendly, intelligent, devoted gundog — the all-American family dog with a golden coat.",
    temperament: ["Friendly", "Intelligent", "Devoted"],
  },
  {
    slug: "german-shepherd",
    name: "German Shepherd",
    group: "herding",
    size: "large",
    origin: "Germany",
    heightMaleMin: 24, heightMaleMax: 26, heightFemaleMin: 22, heightFemaleMax: 24,
    weightMaleMin: 65, weightMaleMax: 90, weightFemaleMin: 50, weightFemaleMax: 70,
    lifespanMin: 9, lifespanMax: 13,
    energy: 5, trainability: 5, shedding: 5, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 5,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 2,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Elbow dysplasia", "Bloat", "Degenerative myelopathy"],
    blurb: "A confident, courageous, and smart working dog — the world's leading police, military, and service breed.",
    temperament: ["Confident", "Courageous", "Smart"],
  },
  {
    slug: "poodle",
    name: "Poodle (Standard)",
    group: "non-sporting",
    size: "large",
    origin: "Germany",
    heightMaleMin: 18, heightMaleMax: 24, heightFemaleMin: 18, heightFemaleMax: 24,
    weightMaleMin: 60, weightMaleMax: 70, weightFemaleMin: 40, weightFemaleMax: 50,
    lifespanMin: 10, lifespanMax: 18,
    energy: 4, trainability: 5, shedding: 1, grooming: 5, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Addison's disease", "Eye disorders"],
    blurb: "An elegant, athletic, and exceptionally intelligent water dog — far more than its show-ring image suggests.",
    temperament: ["Active", "Proud", "Very Smart"],
  },
  {
    slug: "bulldog",
    name: "Bulldog",
    group: "non-sporting",
    size: "medium",
    origin: "England",
    heightMaleMin: 14, heightMaleMax: 15, heightFemaleMin: 14, heightFemaleMax: 15,
    weightMaleMin: 50, weightMaleMax: 50, weightFemaleMin: 40, weightFemaleMax: 40,
    lifespanMin: 8, lifespanMax: 10,
    energy: 2, trainability: 2, shedding: 3, grooming: 2, barking: 1,
    goodWithKids: 5, goodWithDogs: 3, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 3, exerciseNeeds: 2, droolingLevel: 4,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Brachycephalic syndrome", "Hip dysplasia", "Skin fold dermatitis", "Heart issues"],
    blurb: "A calm, courageous, friendly companion — the iconic loose-skinned English mascot breed.",
    temperament: ["Calm", "Courageous", "Friendly"],
  },
  {
    slug: "rottweiler",
    name: "Rottweiler",
    group: "working",
    size: "large",
    origin: "Germany",
    heightMaleMin: 24, heightMaleMax: 27, heightFemaleMin: 22, heightFemaleMax: 25,
    weightMaleMin: 95, weightMaleMax: 135, weightFemaleMin: 80, weightFemaleMax: 100,
    lifespanMin: 9, lifespanMax: 10,
    energy: 4, trainability: 5, shedding: 3, grooming: 2, barking: 2,
    goodWithKids: 4, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 3, intelligence: 5, exerciseNeeds: 4, droolingLevel: 4,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Elbow dysplasia", "Cancer", "Bloat"],
    blurb: "A loyal, loving, confident guardian — descendant of Roman drover dogs, requires firm training.",
    temperament: ["Loyal", "Loving", "Confident Guardian"],
  },
  {
    slug: "beagle",
    name: "Beagle",
    group: "hound",
    size: "small",
    origin: "England",
    heightMaleMin: 13, heightMaleMax: 15, heightFemaleMin: 13, heightFemaleMax: 15,
    weightMaleMin: 20, weightMaleMax: 30, weightFemaleMin: 20, weightFemaleMax: 30,
    lifespanMin: 10, lifespanMax: 15,
    energy: 4, trainability: 3, shedding: 3, grooming: 2, barking: 5,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Obesity", "Epilepsy", "Hypothyroidism", "Ear infections"],
    blurb: "A friendly, curious, merry scenthound — the world's most popular small hound, famous for its bay.",
    temperament: ["Friendly", "Curious", "Merry"],
  },
  {
    slug: "dachshund",
    name: "Dachshund",
    group: "hound",
    size: "small",
    origin: "Germany",
    heightMaleMin: 8, heightMaleMax: 9, heightFemaleMin: 8, heightFemaleMax: 9,
    weightMaleMin: 16, weightMaleMax: 32, weightFemaleMin: 16, weightFemaleMax: 32,
    lifespanMin: 12, lifespanMax: 16,
    energy: 4, trainability: 3, shedding: 3, grooming: 2, barking: 5,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["IVDD (back problems)", "Obesity", "Patellar luxation", "Diabetes"],
    blurb: "A spirited, clever, courageous badger-hunter on stubby legs — the iconic 'wiener dog'.",
    temperament: ["Spunky", "Curious", "Friendly"],
  },
  {
    slug: "yorkshire-terrier",
    name: "Yorkshire Terrier",
    group: "toy",
    size: "toy",
    origin: "England",
    heightMaleMin: 7, heightMaleMax: 8, heightFemaleMin: 7, heightFemaleMax: 8,
    weightMaleMin: 7, weightMaleMax: 7, weightFemaleMin: 7, weightFemaleMax: 7,
    lifespanMin: 11, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 1, grooming: 5, barking: 5,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Tracheal collapse", "Liver shunt", "Dental disease"],
    blurb: "A feisty, brave, tomboyish toy terrier with a glamorous floor-length silk coat.",
    temperament: ["Affectionate", "Sprightly", "Tomboyish"],
  },
  {
    slug: "boxer",
    name: "Boxer",
    group: "working",
    size: "large",
    origin: "Germany",
    heightMaleMin: 23, heightMaleMax: 25, heightFemaleMin: 21.5, heightFemaleMax: 23.5,
    weightMaleMin: 65, weightMaleMax: 80, weightFemaleMin: 50, weightFemaleMax: 65,
    lifespanMin: 10, lifespanMax: 12,
    energy: 5, trainability: 4, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 5, goodWithDogs: 3, goodWithStrangers: 4, protectiveness: 4,
    adaptability: 3, intelligence: 4, exerciseNeeds: 5, droolingLevel: 4,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Cancer", "Heart conditions", "Hip dysplasia", "Bloat"],
    blurb: "A bright, fun-loving, active working dog — eternally puppyish, devoted to family, wary of strangers.",
    temperament: ["Bright", "Fun-Loving", "Active"],
  },
  {
    slug: "siberian-husky",
    name: "Siberian Husky",
    group: "working",
    size: "medium",
    origin: "Siberia",
    heightMaleMin: 21, heightMaleMax: 23.5, heightFemaleMin: 20, heightFemaleMax: 22,
    weightMaleMin: 45, weightMaleMax: 60, weightFemaleMin: 35, weightFemaleMax: 50,
    lifespanMin: 12, lifespanMax: 14,
    energy: 5, trainability: 2, shedding: 5, grooming: 3, barking: 2,
    goodWithKids: 4, goodWithDogs: 5, goodWithStrangers: 4, protectiveness: 1,
    adaptability: 3, intelligence: 4, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye problems", "Hypothyroidism"],
    blurb: "A friendly, mischievous, loyal pack dog bred to pull sleds — known for blue eyes and dramatic howls.",
    temperament: ["Loyal", "Outgoing", "Mischievous"],
  },
  {
    slug: "great-dane",
    name: "Great Dane",
    group: "working",
    size: "giant",
    origin: "Germany",
    heightMaleMin: 30, heightMaleMax: 32, heightFemaleMin: 28, heightFemaleMax: 30,
    weightMaleMin: 140, weightMaleMax: 175, weightFemaleMin: 110, weightFemaleMax: 140,
    lifespanMin: 7, lifespanMax: 10,
    energy: 3, trainability: 4, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 4,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 5,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Bloat", "Hip dysplasia", "Heart disease", "Cancer"],
    blurb: "A friendly, patient, dependable giant — the 'Apollo of dogs' is sweet-natured despite imposing size.",
    temperament: ["Friendly", "Patient", "Dependable"],
  },
  {
    slug: "doberman-pinscher",
    name: "Doberman Pinscher",
    group: "working",
    size: "large",
    origin: "Germany",
    heightMaleMin: 26, heightMaleMax: 28, heightFemaleMin: 24, heightFemaleMax: 26,
    weightMaleMin: 75, weightMaleMax: 100, weightFemaleMin: 60, weightFemaleMax: 90,
    lifespanMin: 10, lifespanMax: 12,
    energy: 5, trainability: 5, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Cardiomyopathy", "Hip dysplasia", "Von Willebrand's disease", "Bloat"],
    blurb: "A loyal, fearless, alert guardian — sleek, athletic, and one of the most intelligent breeds in the world.",
    temperament: ["Loyal", "Fearless", "Alert"],
  },
  {
    slug: "australian-shepherd",
    name: "Australian Shepherd",
    group: "herding",
    size: "medium",
    origin: "USA",
    heightMaleMin: 20, heightMaleMax: 23, heightFemaleMin: 18, heightFemaleMax: 21,
    weightMaleMin: 50, weightMaleMax: 65, weightFemaleMin: 40, weightFemaleMax: 55,
    lifespanMin: 12, lifespanMax: 15,
    energy: 5, trainability: 5, shedding: 4, grooming: 3, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Epilepsy", "Eye problems", "MDR1 gene mutation"],
    blurb: "A smart, work-oriented, exuberant herding dog — actually American despite the name; needs a job.",
    temperament: ["Smart", "Work-Oriented", "Exuberant"],
  },
  {
    slug: "border-collie",
    name: "Border Collie",
    group: "herding",
    size: "medium",
    origin: "Scotland",
    heightMaleMin: 19, heightMaleMax: 22, heightFemaleMin: 18, heightFemaleMax: 21,
    weightMaleMin: 30, weightMaleMax: 55, weightFemaleMin: 30, weightFemaleMax: 55,
    lifespanMin: 12, lifespanMax: 15,
    energy: 5, trainability: 5, shedding: 4, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 2, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Epilepsy", "Collie eye anomaly", "MDR1 gene mutation"],
    blurb: "The world's premier sheep herder and the most intelligent dog breed — a workaholic that needs a purpose.",
    temperament: ["Affectionate", "Smart", "Energetic"],
  },
  {
    slug: "shih-tzu",
    name: "Shih Tzu",
    group: "toy",
    size: "small",
    origin: "Tibet",
    heightMaleMin: 9, heightMaleMax: 10.5, heightFemaleMin: 9, heightFemaleMax: 10.5,
    weightMaleMin: 9, weightMaleMax: 16, weightFemaleMin: 9, weightFemaleMax: 16,
    lifespanMin: 10, lifespanMax: 18,
    energy: 2, trainability: 3, shedding: 1, grooming: 5, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 5, intelligence: 3, exerciseNeeds: 2, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Brachycephalic syndrome", "Eye problems", "Hip dysplasia", "Dental issues"],
    blurb: "An affectionate, playful, outgoing lapdog of Chinese imperial origins — happy as long as it's near you.",
    temperament: ["Affectionate", "Playful", "Outgoing"],
  },
  {
    slug: "cavalier-king-charles-spaniel",
    name: "Cavalier King Charles Spaniel",
    group: "toy",
    size: "small",
    origin: "England",
    heightMaleMin: 12, heightMaleMax: 13, heightFemaleMin: 12, heightFemaleMax: 13,
    weightMaleMin: 13, weightMaleMax: 18, weightFemaleMin: 13, weightFemaleMax: 18,
    lifespanMin: 12, lifespanMax: 15,
    energy: 3, trainability: 4, shedding: 3, grooming: 3, barking: 2,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 1,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Mitral valve disease", "Syringomyelia", "Hip dysplasia", "Eye problems"],
    blurb: "An affectionate, gentle, graceful spaniel — bred as a lapdog companion to British royalty.",
    temperament: ["Affectionate", "Gentle", "Graceful"],
  },
  {
    slug: "miniature-schnauzer",
    name: "Miniature Schnauzer",
    group: "terrier",
    size: "small",
    origin: "Germany",
    heightMaleMin: 12, heightMaleMax: 14, heightFemaleMin: 12, heightFemaleMax: 14,
    weightMaleMin: 11, weightMaleMax: 20, weightFemaleMin: 11, weightFemaleMax: 20,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 4,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Pancreatitis", "Diabetes", "Bladder stones", "Cataracts"],
    blurb: "A friendly, smart, obedient ratter — the eyebrowed, bearded German farm dog scaled down for family life.",
    temperament: ["Friendly", "Smart", "Obedient"],
  },
  {
    slug: "german-shorthaired-pointer",
    name: "German Shorthaired Pointer",
    group: "sporting",
    size: "large",
    origin: "Germany",
    heightMaleMin: 23, heightMaleMax: 25, heightFemaleMin: 21, heightFemaleMax: 23,
    weightMaleMin: 55, weightMaleMax: 70, weightFemaleMin: 45, weightFemaleMax: 60,
    lifespanMin: 10, lifespanMax: 12,
    energy: 5, trainability: 5, shedding: 3, grooming: 1, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Eye conditions", "Lymphedema"],
    blurb: "A friendly, smart, willing-to-please all-around hunting and family dog with a liver-spotted coat.",
    temperament: ["Friendly", "Smart", "Willing to Please"],
  },
  {
    slug: "pembroke-welsh-corgi",
    name: "Pembroke Welsh Corgi",
    group: "herding",
    size: "small",
    origin: "Wales",
    heightMaleMin: 10, heightMaleMax: 12, heightFemaleMin: 10, heightFemaleMax: 12,
    weightMaleMin: 24, weightMaleMax: 30, weightFemaleMin: 24, weightFemaleMax: 28,
    lifespanMin: 12, lifespanMax: 13,
    energy: 4, trainability: 5, shedding: 4, grooming: 2, barking: 4,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 5, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["IVDD", "Hip dysplasia", "Degenerative myelopathy", "Obesity"],
    blurb: "A smart, alert, affectionate herder on stumpy legs — the favorite breed of Queen Elizabeth II.",
    temperament: ["Smart", "Alert", "Affectionate"],
  },
  {
    slug: "australian-cattle-dog",
    name: "Australian Cattle Dog",
    group: "herding",
    size: "medium",
    origin: "Australia",
    heightMaleMin: 18, heightMaleMax: 20, heightFemaleMin: 17, heightFemaleMax: 19,
    weightMaleMin: 35, weightMaleMax: 50, weightFemaleMin: 35, weightFemaleMax: 50,
    lifespanMin: 12, lifespanMax: 16,
    energy: 5, trainability: 5, shedding: 3, grooming: 2, barking: 3,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 2, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Deafness", "Progressive retinal atrophy"],
    blurb: "An alert, curious, pleasant herding dog with a blue or red speckled coat — needs intense daily exercise.",
    temperament: ["Alert", "Curious", "Pleasant"],
  },
  {
    slug: "shetland-sheepdog",
    name: "Shetland Sheepdog",
    group: "herding",
    size: "small",
    origin: "Scotland",
    heightMaleMin: 13, heightMaleMax: 16, heightFemaleMin: 13, heightFemaleMax: 16,
    weightMaleMin: 15, weightMaleMax: 25, weightFemaleMin: 15, weightFemaleMax: 25,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 5, shedding: 4, grooming: 4, barking: 5,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 2, protectiveness: 3,
    adaptability: 4, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Collie eye anomaly", "MDR1 gene mutation", "Hip dysplasia", "Hypothyroidism"],
    blurb: "A bright, playful, energetic miniature Collie from the windswept Shetland Islands — keenly intelligent.",
    temperament: ["Bright", "Playful", "Energetic"],
  },
  {
    slug: "bernese-mountain-dog",
    name: "Bernese Mountain Dog",
    group: "working",
    size: "large",
    origin: "Switzerland",
    heightMaleMin: 25, heightMaleMax: 27.5, heightFemaleMin: 23, heightFemaleMax: 26,
    weightMaleMin: 80, weightMaleMax: 115, weightFemaleMin: 70, weightFemaleMax: 95,
    lifespanMin: 7, lifespanMax: 10,
    energy: 3, trainability: 4, shedding: 5, grooming: 3, barking: 2,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 4,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Cancer", "Hip dysplasia", "Elbow dysplasia", "Bloat"],
    blurb: "A good-natured, calm, strong tri-color farm dog from the Swiss Alps — gentle giants with short lifespans.",
    temperament: ["Good-Natured", "Calm", "Strong"],
  },
  {
    slug: "havanese",
    name: "Havanese",
    group: "toy",
    size: "small",
    origin: "Cuba",
    heightMaleMin: 8.5, heightMaleMax: 11.5, heightFemaleMin: 8.5, heightFemaleMax: 11.5,
    weightMaleMin: 7, weightMaleMax: 13, weightFemaleMin: 7, weightFemaleMax: 13,
    lifespanMin: 14, lifespanMax: 16,
    energy: 3, trainability: 4, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 1,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Hip dysplasia", "Cataracts", "Heart problems"],
    blurb: "An intelligent, outgoing, funny lapdog — Cuba's national dog with a silky, hypoallergenic coat.",
    temperament: ["Intelligent", "Outgoing", "Funny"],
  },
];
