import type { Breed } from "./types";

// Part 3: Hounds & more sporting / working
export const BREEDS_PART3: Breed[] = [
  {
    slug: "basset-hound",
    name: "Basset Hound",
    group: "hound",
    size: "medium",
    origin: "France",
    heightMaleMin: 14, heightMaleMax: 15, heightFemaleMin: 14, heightFemaleMax: 15,
    weightMaleMin: 40, weightMaleMax: 65, weightFemaleMin: 40, weightFemaleMax: 65,
    lifespanMin: 12, lifespanMax: 13,
    energy: 2, trainability: 2, shedding: 4, grooming: 2, barking: 3,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 4, intelligence: 3, exerciseNeeds: 3, droolingLevel: 4,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Bloat", "Ear infections", "Glaucoma", "IVDD", "Obesity"],
    blurb: "A charming, patient, low-key scenthound on stubby legs — Hush Puppies mascot, second-best nose to bloodhound.",
    temperament: ["Charming", "Patient", "Low-Key"],
  },
  {
    slug: "bloodhound",
    name: "Bloodhound",
    group: "hound",
    size: "large",
    origin: "Belgium",
    heightMaleMin: 25, heightMaleMax: 27, heightFemaleMin: 23, heightFemaleMax: 25,
    weightMaleMin: 90, weightMaleMax: 110, weightFemaleMin: 80, weightFemaleMax: 100,
    lifespanMin: 10, lifespanMax: 12,
    energy: 4, trainability: 3, shedding: 3, grooming: 2, barking: 3,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 5,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Bloat", "Hip dysplasia", "Eye conditions", "Ear infections"],
    blurb: "A friendly, independent, inquisitive scenthound — the world's premier nose, used in police tracking.",
    temperament: ["Friendly", "Independent", "Inquisitive"],
  },
  {
    slug: "greyhound",
    name: "Greyhound",
    group: "hound",
    size: "large",
    origin: "Egypt",
    heightMaleMin: 28, heightMaleMax: 30, heightFemaleMin: 27, heightFemaleMax: 28,
    weightMaleMin: 65, weightMaleMax: 70, weightFemaleMin: 60, weightFemaleMax: 65,
    lifespanMin: 10, lifespanMax: 13,
    energy: 3, trainability: 3, shedding: 2, grooming: 1, barking: 1,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Bloat", "Bone cancer", "Anesthesia sensitivity"],
    blurb: "A gentle, independent, noble sighthound — the fastest dog (45 mph) and biggest couch potato off-track.",
    temperament: ["Gentle", "Independent", "Noble"],
  },
  {
    slug: "whippet",
    name: "Whippet",
    group: "hound",
    size: "medium",
    origin: "England",
    heightMaleMin: 19, heightMaleMax: 22, heightFemaleMin: 18, heightFemaleMax: 21,
    weightMaleMin: 25, weightMaleMax: 40, weightFemaleMin: 25, weightFemaleMax: 40,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 3, shedding: 2, grooming: 1, barking: 1,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 2,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Heart disease", "Eye conditions", "Anesthesia sensitivity"],
    blurb: "An affectionate, playful, calm small sighthound — looks like a mini Greyhound, sprints like one too.",
    temperament: ["Affectionate", "Playful", "Calm"],
  },
  {
    slug: "rhodesian-ridgeback",
    name: "Rhodesian Ridgeback",
    group: "hound",
    size: "large",
    origin: "Zimbabwe",
    heightMaleMin: 25, heightMaleMax: 27, heightFemaleMin: 24, heightFemaleMax: 26,
    weightMaleMin: 85, weightMaleMax: 85, weightFemaleMin: 70, weightFemaleMax: 70,
    lifespanMin: 10, lifespanMax: 12,
    energy: 4, trainability: 4, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 5,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Elbow dysplasia", "Dermoid sinus", "Bloat"],
    blurb: "An affectionate, dignified, even-tempered African lion-hunter with a backward ridge of fur down its spine.",
    temperament: ["Affectionate", "Dignified", "Even-Tempered"],
  },
  {
    slug: "afghan-hound",
    name: "Afghan Hound",
    group: "hound",
    size: "large",
    origin: "Afghanistan",
    heightMaleMin: 27, heightMaleMax: 27, heightFemaleMin: 25, heightFemaleMax: 25,
    weightMaleMin: 60, weightMaleMax: 60, weightFemaleMin: 50, weightFemaleMax: 50,
    lifespanMin: 12, lifespanMax: 18,
    energy: 4, trainability: 2, shedding: 2, grooming: 5, barking: 2,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 3,
    adaptability: 3, intelligence: 3, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Cataracts", "Hypothyroidism"],
    blurb: "An aloof, dignified, ancient sighthound — the supermodel of the dog world with a flowing silken coat.",
    temperament: ["Aloof", "Dignified", "Independent"],
  },
  {
    slug: "irish-wolfhound",
    name: "Irish Wolfhound",
    group: "hound",
    size: "giant",
    origin: "Ireland",
    heightMaleMin: 32, heightMaleMax: 34, heightFemaleMin: 30, heightFemaleMax: 32,
    weightMaleMin: 120, weightMaleMax: 120, weightFemaleMin: 105, weightFemaleMax: 105,
    lifespanMin: 6, lifespanMax: 8,
    energy: 3, trainability: 4, shedding: 3, grooming: 2, barking: 1,
    goodWithKids: 5, goodWithDogs: 5, goodWithStrangers: 5, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 2,
    coatLength: "wirehaired", hypoallergenic: false,
    commonHealthIssues: ["Bone cancer", "Heart disease", "Bloat", "Hip dysplasia"],
    blurb: "A courageous, dignified, calm gentle giant — the tallest of all dogs, ancient Celtic war and hunting hound.",
    temperament: ["Courageous", "Dignified", "Calm"],
  },
  {
    slug: "borzoi",
    name: "Borzoi",
    group: "hound",
    size: "large",
    origin: "Russia",
    heightMaleMin: 28, heightMaleMax: 28, heightFemaleMin: 26, heightFemaleMax: 26,
    weightMaleMin: 75, weightMaleMax: 105, weightFemaleMin: 60, weightFemaleMax: 85,
    lifespanMin: 9, lifespanMax: 14,
    energy: 3, trainability: 3, shedding: 4, grooming: 3, barking: 1,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Bloat", "Heart disease", "Anesthesia sensitivity"],
    blurb: "A regal, affectionate, quiet Russian wolfhound — aristocratic sighthound with the long elegant snout.",
    temperament: ["Regal", "Affectionate", "Quiet"],
  },
  {
    slug: "saluki",
    name: "Saluki",
    group: "hound",
    size: "large",
    origin: "Egypt",
    heightMaleMin: 23, heightMaleMax: 28, heightFemaleMin: 23, heightFemaleMax: 28,
    weightMaleMin: 40, weightMaleMax: 65, weightFemaleMin: 40, weightFemaleMax: 65,
    lifespanMin: 10, lifespanMax: 17,
    energy: 4, trainability: 3, shedding: 2, grooming: 2, barking: 1,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 2,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "medium", hypoallergenic: false,
    commonHealthIssues: ["Heart disease", "Cancer", "Anesthesia sensitivity"],
    blurb: "A graceful, dignified, gentle Persian sighthound — one of the world's oldest breeds, depicted on Egyptian tombs.",
    temperament: ["Graceful", "Dignified", "Gentle"],
  },
  {
    slug: "basenji",
    name: "Basenji",
    group: "hound",
    size: "small",
    origin: "Congo",
    heightMaleMin: 17, heightMaleMax: 17, heightFemaleMin: 16, heightFemaleMax: 16,
    weightMaleMin: 24, weightMaleMax: 24, weightFemaleMin: 22, weightFemaleMax: 22,
    lifespanMin: 13, lifespanMax: 14,
    energy: 4, trainability: 3, shedding: 2, grooming: 1, barking: 1,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "short", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Fanconi syndrome", "Hypothyroidism", "PRA"],
    blurb: "An independent, smart, poised African 'barkless dog' — yodel-vocal, cat-like in cleanliness, ancient lineage.",
    temperament: ["Independent", "Smart", "Poised"],
  },
  {
    slug: "bichon-frise",
    name: "Bichon Frise",
    group: "non-sporting",
    size: "small",
    origin: "France",
    heightMaleMin: 9.5, heightMaleMax: 11.5, heightFemaleMin: 9.5, heightFemaleMax: 11.5,
    weightMaleMin: 12, weightMaleMax: 18, weightFemaleMin: 12, weightFemaleMax: 18,
    lifespanMin: 14, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Allergies", "Hip dysplasia", "Patellar luxation", "Cataracts"],
    blurb: "A playful, curious, peppy white powder-puff lapdog from the French Riviera — Mediterranean cheerfulness.",
    temperament: ["Playful", "Curious", "Peppy"],
  },
  {
    slug: "maltese",
    name: "Maltese",
    group: "toy",
    size: "toy",
    origin: "Malta",
    heightMaleMin: 7, heightMaleMax: 9, heightFemaleMin: 7, heightFemaleMax: 9,
    weightMaleMin: 7, weightMaleMax: 7, weightFemaleMin: 7, weightFemaleMax: 7,
    lifespanMin: 12, lifespanMax: 15,
    energy: 3, trainability: 4, shedding: 1, grooming: 5, barking: 4,
    goodWithKids: 3, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Liver shunt", "Dental issues", "White shaker syndrome"],
    blurb: "A gentle, playful, charming aristocrat — ancient Mediterranean lapdog with a flowing snow-white coat.",
    temperament: ["Gentle", "Playful", "Charming"],
  },
  {
    slug: "pomeranian",
    name: "Pomeranian",
    group: "toy",
    size: "toy",
    origin: "Germany",
    heightMaleMin: 6, heightMaleMax: 7, heightFemaleMin: 6, heightFemaleMax: 7,
    weightMaleMin: 3, weightMaleMax: 7, weightFemaleMin: 3, weightFemaleMax: 7,
    lifespanMin: 12, lifespanMax: 16,
    energy: 4, trainability: 3, shedding: 4, grooming: 4, barking: 5,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Tracheal collapse", "Heart disease", "Dental issues"],
    blurb: "A bold, lively, inquisitive fluffy spitz — descended from sled dogs, now under 10 lbs of pure attitude.",
    temperament: ["Bold", "Lively", "Inquisitive"],
  },
  {
    slug: "chihuahua",
    name: "Chihuahua",
    group: "toy",
    size: "toy",
    origin: "Mexico",
    heightMaleMin: 5, heightMaleMax: 8, heightFemaleMin: 5, heightFemaleMax: 8,
    weightMaleMin: 6, weightMaleMax: 6, weightFemaleMin: 6, weightFemaleMax: 6,
    lifespanMin: 14, lifespanMax: 16,
    energy: 4, trainability: 3, shedding: 2, grooming: 2, barking: 5,
    goodWithKids: 2, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Hydrocephalus", "Heart disease", "Dental issues"],
    blurb: "A graceful, charming, sassy tiny dog of Mexican origin — the world's smallest breed, big in personality.",
    temperament: ["Graceful", "Charming", "Sassy"],
  },
  {
    slug: "papillon",
    name: "Papillon",
    group: "toy",
    size: "toy",
    origin: "France",
    heightMaleMin: 8, heightMaleMax: 11, heightFemaleMin: 8, heightFemaleMax: 11,
    weightMaleMin: 5, weightMaleMax: 10, weightFemaleMin: 5, weightFemaleMax: 10,
    lifespanMin: 14, lifespanMax: 16,
    energy: 4, trainability: 5, shedding: 2, grooming: 3, barking: 4,
    goodWithKids: 3, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 2,
    adaptability: 5, intelligence: 5, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Dental issues", "Progressive retinal atrophy"],
    blurb: "A friendly, alert, happy butterfly-eared toy — the most trainable toy breed, fixture in agility podiums.",
    temperament: ["Friendly", "Alert", "Happy"],
  },
  {
    slug: "pug",
    name: "Pug",
    group: "toy",
    size: "small",
    origin: "China",
    heightMaleMin: 10, heightMaleMax: 13, heightFemaleMin: 10, heightFemaleMax: 13,
    weightMaleMin: 14, weightMaleMax: 18, weightFemaleMin: 14, weightFemaleMax: 18,
    lifespanMin: 13, lifespanMax: 15,
    energy: 2, trainability: 3, shedding: 4, grooming: 2, barking: 2,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 5, intelligence: 3, exerciseNeeds: 2, droolingLevel: 3,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Brachycephalic syndrome", "Hip dysplasia", "Eye problems", "Obesity"],
    blurb: "A charming, mischievous, loving wrinkly clown — Chinese imperial lapdog motto: multum in parvo.",
    temperament: ["Charming", "Mischievous", "Loving"],
  },
  {
    slug: "boston-terrier",
    name: "Boston Terrier",
    group: "non-sporting",
    size: "small",
    origin: "USA",
    heightMaleMin: 15, heightMaleMax: 17, heightFemaleMin: 15, heightFemaleMax: 17,
    weightMaleMin: 12, weightMaleMax: 25, weightFemaleMin: 12, weightFemaleMax: 25,
    lifespanMin: 11, lifespanMax: 13,
    energy: 3, trainability: 4, shedding: 2, grooming: 1, barking: 2,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 5, protectiveness: 2,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Brachycephalic syndrome", "Eye problems", "Patellar luxation", "Allergies"],
    blurb: "A friendly, bright, amusing 'American Gentleman' in a tuxedo coat — born in Boston, the original AKC breed.",
    temperament: ["Friendly", "Bright", "Amusing"],
  },
  {
    slug: "miniature-pinscher",
    name: "Miniature Pinscher",
    group: "toy",
    size: "small",
    origin: "Germany",
    heightMaleMin: 10, heightMaleMax: 12.5, heightFemaleMin: 10, heightFemaleMax: 12.5,
    weightMaleMin: 8, weightMaleMax: 12, weightFemaleMin: 8, weightFemaleMax: 12,
    lifespanMin: 12, lifespanMax: 16,
    energy: 5, trainability: 3, shedding: 2, grooming: 1, barking: 4,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Legg-Calve-Perthes disease", "Eye disorders"],
    blurb: "A fearless, energetic, alert 'King of Toys' — looks like a mini Doberman but is actually older.",
    temperament: ["Fearless", "Energetic", "Alert"],
  },
  {
    slug: "italian-greyhound",
    name: "Italian Greyhound",
    group: "toy",
    size: "small",
    origin: "Italy",
    heightMaleMin: 13, heightMaleMax: 15, heightFemaleMin: 13, heightFemaleMax: 15,
    weightMaleMin: 7, weightMaleMax: 14, weightFemaleMin: 7, weightFemaleMax: 14,
    lifespanMin: 14, lifespanMax: 15,
    energy: 4, trainability: 3, shedding: 1, grooming: 1, barking: 3,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 2,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Leg fractures", "Dental issues", "Hypothyroidism", "PRA"],
    blurb: "A playful, alert, sensitive miniature sighthound — Renaissance lapdog favored by Italian nobility.",
    temperament: ["Playful", "Alert", "Sensitive"],
  },
  {
    slug: "lhasa-apso",
    name: "Lhasa Apso",
    group: "non-sporting",
    size: "small",
    origin: "Tibet",
    heightMaleMin: 10, heightMaleMax: 11, heightFemaleMin: 10, heightFemaleMax: 11,
    weightMaleMin: 12, weightMaleMax: 18, weightFemaleMin: 12, weightFemaleMax: 18,
    lifespanMin: 12, lifespanMax: 15,
    energy: 3, trainability: 3, shedding: 1, grooming: 5, barking: 4,
    goodWithKids: 3, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 2, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Eye disorders", "Hip dysplasia", "Skin issues", "Kidney disease"],
    blurb: "A confident, smart, comical Tibetan monastery sentinel — small but feels like a big dog inside.",
    temperament: ["Confident", "Smart", "Comical"],
  },
  {
    slug: "english-mastiff",
    name: "English Mastiff",
    group: "working",
    size: "giant",
    origin: "England",
    heightMaleMin: 30, heightMaleMax: 30, heightFemaleMin: 27.5, heightFemaleMax: 27.5,
    weightMaleMin: 160, weightMaleMax: 230, weightFemaleMin: 120, weightFemaleMax: 170,
    lifespanMin: 6, lifespanMax: 10,
    energy: 2, trainability: 3, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 5,
    adaptability: 3, intelligence: 3, exerciseNeeds: 2, droolingLevel: 5,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Heart disease", "Cancer"],
    blurb: "A courageous, dignified, good-natured giant — the heaviest dog breed, ancient British war hounds.",
    temperament: ["Courageous", "Dignified", "Good-Natured"],
  },
  {
    slug: "bullmastiff",
    name: "Bullmastiff",
    group: "working",
    size: "large",
    origin: "England",
    heightMaleMin: 25, heightMaleMax: 27, heightFemaleMin: 24, heightFemaleMax: 26,
    weightMaleMin: 110, weightMaleMax: 130, weightFemaleMin: 100, weightFemaleMax: 120,
    lifespanMin: 7, lifespanMax: 9,
    energy: 3, trainability: 4, shedding: 2, grooming: 1, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 5,
    adaptability: 3, intelligence: 4, exerciseNeeds: 3, droolingLevel: 5,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Cancer", "Heart problems"],
    blurb: "An affectionate, loyal, brave gamekeeper's night dog — Mastiff-Bulldog cross bred to subdue poachers.",
    temperament: ["Affectionate", "Loyal", "Brave"],
  },
  {
    slug: "cane-corso",
    name: "Cane Corso",
    group: "working",
    size: "large",
    origin: "Italy",
    heightMaleMin: 25, heightMaleMax: 27.5, heightFemaleMin: 23.5, heightFemaleMax: 26,
    weightMaleMin: 99, weightMaleMax: 110, weightFemaleMin: 88, weightFemaleMax: 99,
    lifespanMin: 9, lifespanMax: 12,
    energy: 4, trainability: 4, shedding: 3, grooming: 1, barking: 3,
    goodWithKids: 4, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 5,
    adaptability: 3, intelligence: 4, exerciseNeeds: 4, droolingLevel: 4,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Bloat", "Eye problems", "Cherry eye"],
    blurb: "An assertive, smart, intelligent Italian guard mastiff — Roman war dog turned modern protector.",
    temperament: ["Assertive", "Smart", "Intelligent"],
  },
];
