import type { Breed } from "./types";

// Part 5: More terriers, hounds, sporting
export const BREEDS_PART5: Breed[] = [
  {
    slug: "cairn-terrier",
    name: "Cairn Terrier",
    group: "terrier",
    size: "small",
    origin: "Scotland",
    heightMaleMin: 10, heightMaleMax: 10, heightFemaleMin: 9.5, heightFemaleMax: 9.5,
    weightMaleMin: 14, weightMaleMax: 14, weightFemaleMin: 13, weightFemaleMax: 13,
    lifespanMin: 13, lifespanMax: 15,
    energy: 4, trainability: 3, shedding: 1, grooming: 3, barking: 4,
    goodWithKids: 5, goodWithDogs: 3, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Eye disorders", "Hypothyroidism"],
    blurb: "An alert, cheerful, busy little Scottish ratter — Toto from The Wizard of Oz, the 'small dog with big heart'.",
    temperament: ["Alert", "Cheerful", "Busy"],
  },
  {
    slug: "norfolk-terrier",
    name: "Norfolk Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 9, heightMaleMax: 10, heightFemaleMin: 9, heightFemaleMax: 10,
    weightMaleMin: 11, weightMaleMax: 12, weightFemaleMin: 11, weightFemaleMax: 12,
    lifespanMin: 12, lifespanMax: 16,
    energy: 4, trainability: 4, shedding: 1, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 5, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Patellar luxation", "Eye problems"],
    blurb: "A fearless, alert, gregarious drop-eared terrier — one of the smallest working terriers, fox-bolter.",
    temperament: ["Fearless", "Alert", "Gregarious"],
  },
  {
    slug: "border-terrier",
    name: "Border Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 13, heightMaleMax: 15, heightFemaleMin: 13, heightFemaleMax: 15,
    weightMaleMin: 13, weightMaleMax: 15.5, weightFemaleMin: 11.5, weightFemaleMax: 14,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 2, grooming: 3, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Patellar luxation", "Heart problems"],
    blurb: "An affectionate, intelligent, even-tempered fox-hunting terrier from the English-Scottish border.",
    temperament: ["Affectionate", "Intelligent", "Even-Tempered"],
  },
  {
    slug: "kerry-blue-terrier",
    name: "Kerry Blue Terrier",
    group: "terrier",
    size: "medium",
    origin: "Ireland",
    heightMaleMin: 18, heightMaleMax: 19.5, heightFemaleMin: 17.5, heightFemaleMax: 19,
    weightMaleMin: 33, weightMaleMax: 40, weightFemaleMin: 33, weightFemaleMax: 40,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Cerebellar abiotrophy"],
    blurb: "A smart, alert, people-oriented Irish farmer's all-purpose dog with a famous slate-blue coat.",
    temperament: ["Smart", "Alert", "People-Oriented"],
  },
  {
    slug: "bedlington-terrier",
    name: "Bedlington Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 16, heightMaleMax: 17.5, heightFemaleMin: 15, heightFemaleMax: 16.5,
    weightMaleMin: 17, weightMaleMax: 23, weightFemaleMin: 17, weightFemaleMax: 23,
    lifespanMin: 11, lifespanMax: 16,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Copper toxicosis", "Eye disorders", "Patellar luxation"],
    blurb: "A spirited, demonstrative, mild lamb-shaped terrier — looks like a sheep, fights like a tiger.",
    temperament: ["Spirited", "Demonstrative", "Mild"],
  },
  {
    slug: "manchester-terrier",
    name: "Manchester Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 15, heightMaleMax: 16, heightFemaleMin: 15, heightFemaleMax: 16,
    weightMaleMin: 12, weightMaleMax: 22, weightFemaleMin: 12, weightFemaleMax: 22,
    lifespanMin: 15, lifespanMax: 17,
    energy: 4, trainability: 4, shedding: 2, grooming: 1, barking: 4,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Von Willebrand's disease", "Heart problems", "Eye disorders"],
    blurb: "A keen, devoted, observant English ratter — sleek black-and-tan terrier, gentleman's rat-pit champion.",
    temperament: ["Keen", "Devoted", "Observant"],
  },
  {
    slug: "rat-terrier",
    name: "Rat Terrier",
    group: "terrier",
    size: "small",
    origin: "USA",
    heightMaleMin: 10, heightMaleMax: 18, heightFemaleMin: 10, heightFemaleMax: 18,
    weightMaleMin: 10, weightMaleMax: 25, weightFemaleMin: 10, weightFemaleMax: 25,
    lifespanMin: 12, lifespanMax: 18,
    energy: 5, trainability: 4, shedding: 2, grooming: 1, barking: 3,
    goodWithKids: 4, goodWithDogs: 4, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Hip dysplasia", "Heart issues"],
    blurb: "A friendly, lovable, alert American farm terrier — President Roosevelt's favorite, born to clear vermin.",
    temperament: ["Friendly", "Lovable", "Alert"],
  },
  {
    slug: "soft-coated-wheaten-terrier",
    name: "Soft Coated Wheaten Terrier",
    group: "terrier",
    size: "medium",
    origin: "Ireland",
    heightMaleMin: 18, heightMaleMax: 19, heightFemaleMin: 17, heightFemaleMax: 18,
    weightMaleMin: 35, weightMaleMax: 40, weightFemaleMin: 30, weightFemaleMax: 35,
    lifespanMin: 12, lifespanMax: 14,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 3,
    goodWithKids: 5, goodWithDogs: 4, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Renal dysplasia", "Protein-losing diseases", "Addison's disease"],
    blurb: "A happy, steady, self-confident Irish farm dog with a wheat-colored silky coat — the friendliest terrier.",
    temperament: ["Happy", "Steady", "Self-Confident"],
  },
  {
    slug: "welsh-terrier",
    name: "Welsh Terrier",
    group: "terrier",
    size: "small",
    origin: "Wales",
    heightMaleMin: 15, heightMaleMax: 15.5, heightFemaleMin: 15, heightFemaleMax: 15.5,
    weightMaleMin: 20, weightMaleMax: 20, weightFemaleMin: 20, weightFemaleMax: 20,
    lifespanMin: 12, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 4,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Allergies"],
    blurb: "A spirited, friendly, intelligent Welsh otter and badger hunter — looks like a smaller Airedale.",
    temperament: ["Spirited", "Friendly", "Intelligent"],
  },
  {
    slug: "australian-terrier",
    name: "Australian Terrier",
    group: "terrier",
    size: "small",
    origin: "Australia",
    heightMaleMin: 10, heightMaleMax: 11, heightFemaleMin: 10, heightFemaleMax: 11,
    weightMaleMin: 15, weightMaleMax: 20, weightFemaleMin: 15, weightFemaleMax: 20,
    lifespanMin: 11, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 2, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Diabetes", "Allergies"],
    blurb: "A spirited, alert, courageous Australian outback ratter — the first breed developed Down Under.",
    temperament: ["Spirited", "Alert", "Courageous"],
  },
  {
    slug: "lakeland-terrier",
    name: "Lakeland Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 14, heightMaleMax: 15, heightFemaleMin: 14, heightFemaleMax: 15,
    weightMaleMin: 17, weightMaleMax: 17, weightFemaleMin: 17, weightFemaleMax: 17,
    lifespanMin: 12, lifespanMax: 16,
    energy: 4, trainability: 4, shedding: 1, grooming: 4, barking: 4,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Patellar luxation", "Eye problems", "Legg-Calve-Perthes"],
    blurb: "A bold, friendly, confident terrier from England's Lake District — fox-hunter with a square jaw.",
    temperament: ["Bold", "Friendly", "Confident"],
  },
  {
    slug: "skye-terrier",
    name: "Skye Terrier",
    group: "terrier",
    size: "small",
    origin: "Scotland",
    heightMaleMin: 10, heightMaleMax: 10, heightFemaleMin: 9.5, heightFemaleMax: 9.5,
    weightMaleMin: 35, weightMaleMax: 45, weightFemaleMin: 25, weightFemaleMax: 35,
    lifespanMin: 12, lifespanMax: 14,
    energy: 3, trainability: 3, shedding: 2, grooming: 4, barking: 3,
    goodWithKids: 3, goodWithDogs: 2, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 3, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Hyperthyroidism"],
    blurb: "A courageous, canny, fearless Scottish island terrier — once Queen Victoria's favorite, now rare.",
    temperament: ["Courageous", "Canny", "Fearless"],
  },
  {
    slug: "smooth-fox-terrier",
    name: "Smooth Fox Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 15, heightMaleMax: 15, heightFemaleMin: 15, heightFemaleMax: 15,
    weightMaleMin: 17, weightMaleMax: 19, weightFemaleMin: 15, weightFemaleMax: 17,
    lifespanMin: 12, lifespanMax: 15,
    energy: 5, trainability: 4, shedding: 3, grooming: 1, barking: 4,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 4, protectiveness: 3,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Eye disorders", "Deafness"],
    blurb: "A friendly, independent, amusing English fox-bolter — sleek smooth-coated cousin of Wire Fox.",
    temperament: ["Friendly", "Independent", "Amusing"],
  },
  {
    slug: "irish-terrier",
    name: "Irish Terrier",
    group: "terrier",
    size: "medium",
    origin: "Ireland",
    heightMaleMin: 18, heightMaleMax: 18, heightFemaleMin: 18, heightFemaleMax: 18,
    weightMaleMin: 27, weightMaleMax: 27, weightFemaleMin: 25, weightFemaleMax: 25,
    lifespanMin: 13, lifespanMax: 15,
    energy: 4, trainability: 4, shedding: 1, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 2, goodWithStrangers: 4, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "wirehaired", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Hyperkeratosis", "Eye disorders"],
    blurb: "A bold, dashing, tenderhearted Irish 'daredevil' — fiery red-coated farm dog and WWI message-runner.",
    temperament: ["Bold", "Dashing", "Tenderhearted"],
  },
  {
    slug: "miniature-bull-terrier",
    name: "Miniature Bull Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 10, heightMaleMax: 14, heightFemaleMin: 10, heightFemaleMax: 14,
    weightMaleMin: 18, weightMaleMax: 28, weightFemaleMin: 18, weightFemaleMax: 28,
    lifespanMin: 11, lifespanMax: 13,
    energy: 4, trainability: 3, shedding: 3, grooming: 1, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 4, exerciseNeeds: 4, droolingLevel: 2,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Deafness", "Patellar luxation", "Heart issues", "Skin problems"],
    blurb: "A playful, charming, mischievous mini version of the Bull Terrier — same egg-head, smaller package.",
    temperament: ["Playful", "Charming", "Mischievous"],
  },
  {
    slug: "russell-terrier",
    name: "Russell Terrier",
    group: "terrier",
    size: "small",
    origin: "England",
    heightMaleMin: 10, heightMaleMax: 12, heightFemaleMin: 10, heightFemaleMax: 12,
    weightMaleMin: 9, weightMaleMax: 15, weightFemaleMin: 9, weightFemaleMax: 15,
    lifespanMin: 12, lifespanMax: 14,
    energy: 5, trainability: 3, shedding: 3, grooming: 1, barking: 4,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 3,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Patellar luxation", "Eye disorders", "Deafness"],
    blurb: "A lively, alert, inquisitive English fox-bolter — shorter-legged cousin of Jack Russell, equally feisty.",
    temperament: ["Lively", "Alert", "Inquisitive"],
  },
  {
    slug: "bouvier-des-flandres",
    name: "Bouvier des Flandres",
    group: "herding",
    size: "large",
    origin: "Belgium",
    heightMaleMin: 24.5, heightMaleMax: 27.5, heightFemaleMin: 23.5, heightFemaleMax: 26.5,
    weightMaleMin: 70, weightMaleMax: 110, weightFemaleMin: 70, weightFemaleMax: 110,
    lifespanMin: 10, lifespanMax: 12,
    energy: 4, trainability: 4, shedding: 2, grooming: 4, barking: 2,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 5,
    adaptability: 3, intelligence: 5, exerciseNeeds: 4, droolingLevel: 3,
    coatLength: "long", hypoallergenic: true,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Bloat"],
    blurb: "A courageous, strong-willed, devoted Belgian cattle drover — bearded farm guardian and WWI ambulance dog.",
    temperament: ["Courageous", "Strong-Willed", "Devoted"],
  },
  {
    slug: "belgian-tervuren",
    name: "Belgian Tervuren",
    group: "herding",
    size: "large",
    origin: "Belgium",
    heightMaleMin: 24, heightMaleMax: 26, heightFemaleMin: 22, heightFemaleMax: 24,
    weightMaleMin: 55, weightMaleMax: 75, weightFemaleMin: 45, weightFemaleMax: 60,
    lifespanMin: 12, lifespanMax: 14,
    energy: 5, trainability: 5, shedding: 4, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Epilepsy", "Eye disorders"],
    blurb: "A courageous, smart, alert Belgian shepherd — long-haired cousin of the Malinois with rich mahogany coat.",
    temperament: ["Courageous", "Smart", "Alert"],
  },
  {
    slug: "belgian-sheepdog",
    name: "Belgian Sheepdog (Groenendael)",
    group: "herding",
    size: "large",
    origin: "Belgium",
    heightMaleMin: 24, heightMaleMax: 26, heightFemaleMin: 22, heightFemaleMax: 24,
    weightMaleMin: 55, weightMaleMax: 75, weightFemaleMin: 45, weightFemaleMax: 60,
    lifespanMin: 12, lifespanMax: 14,
    energy: 5, trainability: 5, shedding: 4, grooming: 3, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 2, protectiveness: 4,
    adaptability: 3, intelligence: 5, exerciseNeeds: 5, droolingLevel: 1,
    coatLength: "long", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Epilepsy", "Eye disorders"],
    blurb: "A bright, watchful, serious-minded Belgian shepherd — black long-haired version, all energy and brain.",
    temperament: ["Bright", "Watchful", "Serious-Minded"],
  },
  {
    slug: "german-pinscher",
    name: "German Pinscher",
    group: "working",
    size: "medium",
    origin: "Germany",
    heightMaleMin: 17, heightMaleMax: 20, heightFemaleMin: 17, heightFemaleMax: 20,
    weightMaleMin: 25, weightMaleMax: 45, weightFemaleMin: 25, weightFemaleMax: 45,
    lifespanMin: 12, lifespanMax: 14,
    energy: 5, trainability: 4, shedding: 3, grooming: 1, barking: 3,
    goodWithKids: 4, goodWithDogs: 3, goodWithStrangers: 3, protectiveness: 4,
    adaptability: 4, intelligence: 5, exerciseNeeds: 4, droolingLevel: 1,
    coatLength: "short", hypoallergenic: false,
    commonHealthIssues: ["Hip dysplasia", "Eye disorders", "Heart problems"],
    blurb: "A spirited, smart, observant German farm and stable ratter — between Mini Pinscher and Doberman in size.",
    temperament: ["Spirited", "Smart", "Observant"],
  },
];
